/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as ProcessandoRouteImport } from './routes/processando'
import { Route as InteresseRouteImport } from './routes/interesse'
import { Route as CartaoAprovadoRouteImport } from './routes/cartao-aprovado'
import { Route as AprovadoRouteImport } from './routes/aprovado'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessandoRoute = ProcessandoRouteImport.update({
  id: '/processando',
  path: '/processando',
  getParentRoute: () => rootRouteImport,
} as any)
const InteresseRoute = InteresseRouteImport.update({
  id: '/interesse',
  path: '/interesse',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoAprovadoRoute = CartaoAprovadoRouteImport.update({
  id: '/cartao-aprovado',
  path: '/cartao-aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovadoRoute = AprovadoRouteImport.update({
  id: '/aprovado',
  path: '/aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/cartao-aprovado': typeof CartaoAprovadoRoute
  '/interesse': typeof InteresseRoute
  '/processando': typeof ProcessandoRoute
  '/questionario': typeof QuestionarioRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/cartao-aprovado': typeof CartaoAprovadoRoute
  '/interesse': typeof InteresseRoute
  '/processando': typeof ProcessandoRoute
  '/questionario': typeof QuestionarioRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/cartao-aprovado': typeof CartaoAprovadoRoute
  '/interesse': typeof InteresseRoute
  '/processando': typeof ProcessandoRoute
  '/questionario': typeof QuestionarioRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovado'
    | '/cartao-aprovado'
    | '/interesse'
    | '/processando'
    | '/questionario'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovado'
    | '/cartao-aprovado'
    | '/interesse'
    | '/processando'
    | '/questionario'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/aprovado'
    | '/cartao-aprovado'
    | '/interesse'
    | '/processando'
    | '/questionario'
    | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprovadoRoute: typeof AprovadoRoute
  CartaoAprovadoRoute: typeof CartaoAprovadoRoute
  InteresseRoute: typeof InteresseRoute
  ProcessandoRoute: typeof ProcessandoRoute
  QuestionarioRoute: typeof QuestionarioRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processando': {
      id: '/processando'
      path: '/processando'
      fullPath: '/processando'
      preLoaderRoute: typeof ProcessandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesse': {
      id: '/interesse'
      path: '/interesse'
      fullPath: '/interesse'
      preLoaderRoute: typeof InteresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao-aprovado': {
      id: '/cartao-aprovado'
      path: '/cartao-aprovado'
      fullPath: '/cartao-aprovado'
      preLoaderRoute: typeof CartaoAprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovado': {
      id: '/aprovado'
      path: '/aprovado'
      fullPath: '/aprovado'
      preLoaderRoute: typeof AprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprovadoRoute: AprovadoRoute,
  CartaoAprovadoRoute: CartaoAprovadoRoute,
  InteresseRoute: InteresseRoute,
  ProcessandoRoute: ProcessandoRoute,
  QuestionarioRoute: QuestionarioRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
